export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER = 'SET_USER';
export const LOADING_USER = 'LOADING_USER';
export const MARK_NOTIFICATIONS_READ = 'MARK_NOTIFICATIONS_READ'; 

export const SET_ERRORS = 'SET_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const SET_POSTS = "SET_POSTS";
export const SET_FIRST_SET_OF_POSTS = "SET_FIRST_SET_OF_POSTS";
export const SET_MORE_POSTS = "SET_MORE_POSTS";
export const SET_POST = "SET_POST";
export const LOADING_DATA = "LOADING_DATA";
export const LIKE_POST = "LIKE_POST";
export const UNLIKE_POST = "UNLIKE_POST";
export const DELETE_POST = "DELETE_POST";
export const LIKE_COMMENT = 'LIKE_COMMENT';
export const UNLIKE_COMMENT = 'UNLIKE_COMMENT';
export const POST_A_POST = 'POST_A_POST';
export const COMMENT_A_POST = 'COMMENT_A_POST';
export const DELETE_A_COMMENT = 'DELETE_A_COMMENT';
export const GET_USERS = 'GET_USERS';
export const GET_SINGLE_USER = 'GET_SINGLE_USER';
export const GET_USER = 'GET_USER';

export const OPEN_CARD_PROFILE = 'OPEN_CARD_PROFILE';
export const CLOSE_CARD_PROFILE = 'CLOSE_CARD_PROFILE';